### PR TITLE
Add build for nodejs v18

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://github.com/stolostron/backlog/issues/25555

### CODE REVIEW

**Comment by ray-harris** [comment]
@KevinFCormier Can you change the version of Go in the Dockerfile to 1.19.2 please?

**Comment by KevinFCormier** [comment]
@ray-harris Should we update the nodejs 14 and 16 images this way as well? There is no nodejs 18 available in UBI yet, but this PR is passing since I haven't made the update in `openshift/release` yet to build this image. I suppose we could go ahead and merge it and just update the config to actually build it once it is available. Or we can update Go versions in another PR. Thoughts?

**Comment by ray-harris** [comment]
I updated the other NodeJS images to Go 1.18.7 a couple of days ago in this PR:
https://github.com/stolostron/image-builder/pull/118

Apparently I wasn't paying close attention and probably should have updated them to 1.19.2. As long as it's 1.18.7 or 1.19.2 it'll be fine as those are the current supported versions.

**Review by smithbw88 — APPROVED** [review]
LGTM

**Pull request merged**
