### PR TITLE
Add a Go 1.22 builder and update 1.21 and 1.20

### PR DESCRIPTION
**Pull request by skitt**
(1.20 is EOL but we might as well use the last version.)

### CODE REVIEW

**Comment by tpantelis** [comment]
@arewm @gurnben Can you please review/merge this PR? It's blocking progress...

**Comment by tpantelis** [comment]
Looking at the output release job: https://storage.googleapis.com/test-platform-results/logs/branch-ci-stolostron-image-builder-master-images/1790550283185557504/build-log.txt, I don't see any reference to it building a go 1.22 image. Shoild it have?

**Comment by skitt** [comment]
> Looking at the output from the release job: https://storage.googleapis.com/test-platform-results/logs/branch-ci-stolostron-image-builder-master-images/1790550283185557504/build-log.txt, I don't see any reference to it building a go 1.22 image. Should it have?

@gurnben is this one of those situations where we need a follow-up dummy commit to actually trigger the image builds?

**Comment by gurnben** [comment]
@skitt yepp, that's it!

**Comment by skitt** [comment]
Ah, but only after the openshift/release configuration has been updated, IIRC. So once https://github.com/openshift/release/pull/52052 (or at least the `image-builder` part) goes in, we need a dummy PR like #134 to actually get the image.

**Pull request merged**
